apiVersion: v1
kind: Service
metadata:
  name: commandsideservice-lb
spec:
  selector:
    app: spring-commandsideservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
