stages:         
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - ./build.sh $* -P eventuateDriver=local
    - echo "Build completed"

e2e-test-job:   
  stage: test    
  script:
    - ./test.sh $* -P eventuateDriver=local
    - echo "E2E tests completed"

push-images-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
