version: 2.1
parameters:
  restore_cache_prefix:
    description: set to random value to disable cache restoration
    type: string
    default: ''
orbs:
  build-and-test:
    jobs:
      build-and-test:
        parameters:
          script:
            description: the script to execute
            type: string
          resource_class:
            description: the resource class
            type: string
            default: 'medium'
          maven_cache_command:
            description: maven command to run
            type: string
            default: ''
          restore_cache_prefix:
            description: set to random value to disable cache restoration
            type: string
            default: ''
        machine:
          image: ubuntu-2004:202101-01
        resource_class: <<parameters.resource_class>>
        working_directory: ~/eventuate-tram-examples-customers-and-orders
        environment:
          # Customize the JVM maximum heap limit
          JVM_OPTS: -Xmx256m
          TERM: dumb
        steps:
          - checkout
          - run: |
              ./.circleci/install-java-11.sh
          - restore_cache:
              keys:
                - << parameters.restore_cache_prefix >>eventuate-tram-examples-customers-and-orders-j8-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                - << parameters.restore_cache_prefix >>eventuate-tram-examples-customers-and-orders-j8-
          - run:
              command: |
                . ./.circleci/setenv-circle-ci.sh
                ./gradlew testClasses
                <<parameters.maven_cache_command>>
          - save_cache:
              paths:
                - ~/.gradle
                - ~/.m2
              key: eventuate-tram-examples-customers-and-orders-j8-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          - run:
              command: |
                . ./.circleci/setenv-circle-ci.sh
                <<parameters.script>>
          - run:
              name: Save test results
              command: |
                mkdir -p ~/junit
                find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
              when: always
          - run:
              name: Print container logs
              command: |
                ./.circleci/print-container-logs.sh
              when: always
          - store_test_results:
              path: ~/junit
          - store_artifacts:
              path: ~/junit
          - store_artifacts:
              path: ~/container-logs
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build-and-test/build-and-test:
          name: mysql
          script: ./build-and-test-all-mysql.sh
          restore_cache_prefix: "<<pipeline.parameters.restore_cache_prefix>>"
      - build-and-test/build-and-test:
          name: postgres-polling
          script: ./build-and-test-all-postgres-polling.sh
          restore_cache_prefix: "<<pipeline.parameters.restore_cache_prefix>>"
      - build-and-test/build-and-test:
          name: postgres-wal
          script: ./build-and-test-all-postgres-wal.sh
          restore_cache_prefix: "<<pipeline.parameters.restore_cache_prefix>>"
