---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: spring-app
data:
  #Kafka
  KAFKA_LISTENERS: LC://kafka-service:29092,LX://kafka-service:9092
  KAFKA_ADVERTISED_LISTENERS: LC://kafka-service:29092,LX://kafka-service:9092
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: LC
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_HEAP_OPTS: -Xmx192m

  #cdcservice
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service/eventuate
  SPRING_DATASOURCE_USERNAME: mysqluser
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka-service:29092
  EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper-service:2181
  EVENTUATELOCAL_CDC_DB_USER_NAME: root
  EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
  EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
  EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: MySqlBinlog
  EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 1234567890
  EVENTUATE_OUTBOX_ID: 1
  EVENTUATE_CDC_TYPE: EventuateLocal

  #mysql
  MYSQL_USER: mysqluser