apiVersion: v1
kind: Service
metadata:
  name: cdcservice-service
  namespace: spring-app
spec:
  ports:
  - name: cdcservice-port
    targetPort: 8080
    port: 8099
    protocol: TCP
  selector:
    app: spring-cdcservice