---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: spring-app
  labels:
    app: spring-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kafka
  template:
    metadata:
      labels:
        app: spring-kafka
    spec:
      containers:
      - name: kafka-pod
        image: eventuateio/eventuate-kafka
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: KAFKA_LISTENERS
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: KAFKA_ADVERTISED_LISTENERS
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: KAFKA_INTER_BROKER_LISTENER_NAME
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: KAFKA_ZOOKEEPER_CONNECT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        - name: KAFKA_HEAP_OPTS
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: KAFKA_HEAP_OPTS