apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: spring-app
spec:
  ports:
  - name: kafka-port1
    targetPort: 9092
    port: 9092
    protocol: TCP
  - name: kafka-port2
    targetPort: 29092
    port: 29092
    protocol: TCP
  selector:
    app: spring-kafka