---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: spring-app
spec:
  ports:
    targetPort: 2181
    port: 2181
    protocol: TCP
  selector:
    app: spring-zookeeper