---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: spring-app
  labels:
    app: spring-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mysql
  template:
    metadata:
      labels:
        app: spring-mysql
    spec:
      containers:
      - name: mysql-pod
        image: #do wbicia
        ports:
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapRef:
              name: app-configmap
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-configmap
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-configmap
              key: MYSQL_PASSWORD
