apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: spring-app
spec:
  ports:
  - name: mysql-port
    targetPort: 3306
    port: 3306
    protocol: TCP
  selector:
    app: spring-mysql